# -*- coding: utf-8 -*-
"""VCC_Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-k_Xn2k8MbUzPD-aM771bwo7dT7SJfls
"""

#Install python and Python flask using below commands in both the Vm’s:

sudo apt update
sudo apt install python3-pip
pip3 install flask

#after installing Python and Flask in both the VM’s

'''execute below commands in Virtual machine 1 only.
then make file with your name  '''

nano zarrish.py

#Now write below code in the terminal

from flask import Flask

app = Flask(__name__)

@app.route('/')
def home():
    return 'Hello from the Flask API server!'

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)

'''Press Ctrl + x
The give Y
Then Press Enter
Then execute below command '''

python3 sachin.py

#Now In Virtual Machine -2 install curl using below commands

sudo snap install curl

# Then execute below commands to check the final

curl http://192.168.56.102:5000